#!/usr/bin/env bun
/**
 * Local development setup — writes .dev.vars with localhost runtime-var
 * overrides and freshly generated random secrets. Runs only for local dev;
 * the Deploy-to-Cloudflare flow uses scripts/deploy.ts instead.
 *
 * Runtime vars that have defaults in wrangler.jsonc (APP_NAME,
 * LLM_DEFAULT_MODEL) are NOT redeclared here — wrangler dev reads them
 * from wrangler.jsonc. Provider API keys are NOT included either; add
 * them in the app UI (Settings → LLM providers) or append manually here.
 */
import { existsSync, writeFileSync } from 'node:fs';

function randomHex(bytes = 32): string {
  const a = new Uint8Array(bytes);
  crypto.getRandomValues(a);
  return Array.from(a, (b) => b.toString(16).padStart(2, '0')).join('');
}

const path = '.dev.vars';
if (existsSync(path)) {
  console.log('.dev.vars already exists — leaving as-is.');
  process.exit(0);
}

const contents = `# Local dev secrets — generated by \`bun run setup\`.
COOKIE_SIGNING_KEY=${randomHex(32)}
ADMIN_SETUP_TOKEN=${randomHex(16)}

# Add provider API keys here for local dev, or use in-app BYOK
# at Settings → LLM providers (preferred — scoped per workspace).
# OPENAI_API_KEY=
# ANTHROPIC_API_KEY=
# GOOGLE_AI_STUDIO_API_KEY=
# GROK_API_KEY=
# OPENROUTER_API_KEY=
`;

writeFileSync(path, contents, { mode: 0o600 });
console.log(`✓ wrote ${path} with localhost overrides + generated secrets`);
console.log('  Next: bun run db:migrate:local && bun run dev');
